PersonalPage/apps/entries/urls.py
from django.conf.urls import url
from entries.views import EntryView

urlpatterns = [
    url(r'^(?P<entry_sname>[a-zA-Z-0-9]*)/$', EntryView.as_view(), name='entry'),
]

PersonalPage/apps/games/urls.py
from django.conf.urls import url
from games.views import GameView

urlpatterns = [
    url(r'^(?P<game_sname>[a-zA-Z-0-9]*)/$', GameView.as_view(), name='game'),
]

PersonalPage/apps/projects/urls.py
from django.conf.urls import url
from projects.views import ProjectView, CategoryView

urlpatterns = [
    url(r'^(?P<category_sname>[a-zA-Z-0-9]*)/$', CategoryView.as_view(), name='category'),
    url(r'^(?P<category_sname>[a-zA-Z-0-9]*)/(?P<project_sname>[a-zA-Z-0-9]*)/$', ProjectView.as_view(), name='project'),
]

PersonalPage/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from PersonalPage.views import index, game

urlpatterns = i18n_patterns(
    url(r'^$', index, name='home'),
    url(r'^game/$', game, name='game'),
    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^entries/', include('entries.urls', namespace='entries')),
    url(r'^games/', include('games.urls', namespace='games')),
    url(r'^admin/', include(admin.site.urls)),
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

from sitetree.sitetreeapp import register_i18n_trees
register_i18n_trees(['main'])

PersonalPage/apps/entries/models.py
from django.db import models
from multilingual_model.models import MultilingualModel, MultilingualTranslation


class Entry(MultilingualModel):
    sname = models.SlugField(primary_key=True)

    def __str__(self):
        return self.sname


class EntryTranslation(MultilingualTranslation):
    class Meta:
        unique_together = ('parent', 'language_code')

    parent = models.ForeignKey(Entry, related_name='translations')
    header = models.CharField(max_length=200)
    text = models.TextField()

PersonalPage/apps/games/models.py
from django.db import models


class Game(models.Model):
    sname = models.SlugField(primary_key=True)
    template_path = models.CharField(max_length=200)

    def __str__(self):
        return self.sname

PersonalPage/apps/projects/models.py
from django.db import models
from multilingual_model.models import MultilingualModel, MultilingualTranslation
from sorl.thumbnail import ImageField


class Category(MultilingualModel):
    sname = models.SlugField(primary_key=True)

    def __str__(self):
        return self.name


class CategoryTranslation(MultilingualTranslation):
    class Meta:
        unique_together = ('parent', 'language_code')

    parent = models.ForeignKey('Category', related_name='translations')
    name = models.CharField(max_length=200)


class Project(MultilingualModel):
    sname = models.SlugField(primary_key=True)
    name = models.CharField(max_length=200)
    date = models.DateField(blank=True)
    tech = models.CharField(max_length=200, blank=True)
    url = models.URLField(blank=True)
    zip = models.FileField(upload_to='files/', blank=True, null=True)
    categories = models.ManyToManyField(Category, related_name="projects")
    def __str__(self):
        return self.name


class Picture(models.Model):
    project = models.ForeignKey(Project, related_name="pictures")
    pic = ImageField(upload_to='images/', blank=True, null=True)


class ProjectTranslation(MultilingualTranslation):
    class Meta:
        unique_together = ('parent', 'language_code')

    parent = models.ForeignKey('Project', related_name='translations')
    description = models.TextField(blank=True)
    kind = models.CharField(max_length=200)

PersonalPage/apps/entries/views.py
from django.views.generic import DetailView
from entries.models import Entry


class EntryView(DetailView):
    model = Entry
    template_name = "entry.html"
    context_object_name = 'entry'
    slug_field = 'sname'
    slug_url_kwarg = 'entry_sname'

PersonalPage/apps/games/views.py
from django.views.generic import View
from django.views.generic.detail import SingleObjectMixin
from django.shortcuts import render
from games.models import Game


class GameView(SingleObjectMixin, View):
    model = Game
    slug_field = 'sname'
    slug_url_kwarg = 'game_sname'

    def get(self, request, *args, **kwargs):
        return render(request, self.get_object().template_path)

PersonalPage/apps/projects/views.py
from django.views.generic import DetailView
from projects.models import Project, Category


class CategoryView(DetailView):
    template_name = "projects/category.html"
    model = Category
    context_object_name = 'category'
    slug_field = 'sname'
    slug_url_kwarg = 'category_sname'


class ProjectView(DetailView):
    model = Project
    template_name = "projects/project.html"
    context_object_name = 'project'
    slug_field = 'sname'
    slug_url_kwarg = 'project_sname'

PersonalPage/views.py
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render


def index(request):
    return HttpResponseRedirect(reverse('entries:entry', args=('home',)))


def game(request):
    return render(request, 'game.html')

PersonalPage/templates/base.html
{% load staticfiles sitetree i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html>
    <head>
        <title>Илья Гусев / Ilya Gusev</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Ilya Gusev">
        <meta name="google-site-verification" content="zgDC_JybyLZopJzEzwY_PCQhuN2ig3MlqpAuWWnvG60" />
        {% block js %}
        {% endblock js %}
        <script type="text/javascript" src="{% static 'lib/jquery/js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
        {% block css %}
        {% endblock css %}
        <link rel="stylesheet" href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'lib/bootstrap/css/bootstrap-theme.min.css' %}" type="text/css">
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
        <link rel="alternate" href="http://ilyagusev.ru/en" hreflang="en" />
        <link rel="alternate" href="http://ilyagusev.ru/ru" hreflang="x-default" />
    </head>
    <body style="padding-top:60px">
        <div class="navbar navbar-fixed-top navbar-inverse">
            <div class="container">
                <div class="navbar-header">
                     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                    <a class="navbar-brand" href="{% url 'entries:entry' entry_sname='home' %}">
                        {% trans "Ilya Gusev" %}
                    </a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    {% sitetree_menu from "main" include "trunk" template "sitetree/menu_bootstrap3.html" %}
                    {% if LANGUAGE_CODE == "ru" %}
                    <form class="navbar-form navbar-right" action="/en">
                    {% else %}
                    <form class="navbar-form navbar-right" action="/ru">
                    {% endif %}
                        <button type="submit" class="btn btn-info">{% trans "English version" %}</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

PersonalPage/templates/entry.html
{% extends "base.html" %}
{% block content %}
<div style="padding-top:40px">
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped">
                <tr><td><h2>{{ entry.header }}</h2></td></tr>
                {{ entry.text|safe }}
            </table>
        </div>
    </div>
</div>
{% endblock content %}

PersonalPage/templates/projects/category.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
 <div class="col-md-12 category-main" style="padding-top:40px">
    {% if category.projects.all %}
        <div class="col-md-12"> <h2>{{category.name}}</h2></div>
        <table class="table table-striped">
            <thead>
                <th>{% trans "Name" %}</th>
                <th>{% trans "Kind" %}</th>
                <th>{% trans "Technologies" %}</th>
            </thead>
            <tbody>
                {% for project in category.projects.all %}
                <tr>
                    <td><a href="{% url 'projects:project' category.sname project.sname %}"> {{ project.name }} </a></td>
                    <td> {{ project.kind }}</td>
                    <td> {{ project.tech }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h2>{% trans "No projects found." %}</h2>
    {% endif %}
</div>
{% endblock content %}

PersonalPage/templates/projects/project.html
{% extends "base.html" %}
{% block content %}
{% load thumbnail i18n %}
<div style="padding-top:40px">
    <div class="row">
        <div class="col-sm-9 project-main">
            <table class="table">
            <tr><td><h3>{{ project.name }}</h3></td></tr>
            <tr><td><p>{{ project.description }}</p></td></tr>
            </table>
        </div>
        <div class="col-sm-3 project-sidebar">
            <table class="table table-striped">
                <tr><td width=40%>{% trans "What is it:" %} </td><td>{{project.kind}}</td></p></tr>
                <tr><td>{% trans "Release date:" %} </td><td>{{project.date}}</td></tr>
                <tr><td>{% trans "Technologies:" %} </td><td>{{project.tech}}</td></tr>
                <tr><td colspan=2 align="center"><a href="{{ project.url }}">{% trans "URL" %}</a></td></tr>
                <tr><td colspan=2 align="center"><a href="{{MEDIA_URL}}{{ project.zip }}">{% trans "Download ZIP" %}</a></td></tr>
            </table>
        </div>
    </div>
    {% if project.pictures.all %}
    <div class="row">
        <div class="col-sm-12 project-screens">
            <h4>{% trans "Screenshots:" %}</h4>
            {% for picture in project.pictures.all %}
                {% thumbnail picture.pic "150x150" crop="center" as pic %}
                    <a href="{{MEDIA_URL}}{{picture.pic}}"><img src="{{ pic.url }}"></a>
                {% endthumbnail %}
            {% endfor %}
        </div>
    </div>
    {% endif %}
</div>
{% endblock content %}